"""Canonical seed dataset for the Real Estate quant module."""

REAL_ESTATE_SEED_DATA = [
    {
        "comuna": "Ñuñoa",
        "segment_type": "Mid-Market",
        "uf_m2": 86.4,
        "gross_cap_rate": 0.0470,
        "net_cap_rate": 0.0340,
        "vacancy_rate": 0.0610,
        "days_on_market": 34,
    },
    {
        "comuna": "Providencia",
        "segment_type": "Premium",
        "uf_m2": 102.1,
        "gross_cap_rate": 0.0410,
        "net_cap_rate": 0.0300,
        "vacancy_rate": 0.0420,
        "days_on_market": 39,
    },
    {
        "comuna": "Las Condes",
        "segment_type": "Premium",
        "uf_m2": 114.8,
        "gross_cap_rate": 0.0370,
        "net_cap_rate": 0.0270,
        "vacancy_rate": 0.0380,
        "days_on_market": 43,
    },
    {
        "comuna": "Vitacura",
        "segment_type": "Premium",
        "uf_m2": 128.3,
        "gross_cap_rate": 0.0340,
        "net_cap_rate": 0.0240,
        "vacancy_rate": 0.0310,
        "days_on_market": 48,
    },
    {
        "comuna": "Lo Barnechea",
        "segment_type": "Premium",
        "uf_m2": 118.0,
        "gross_cap_rate": 0.0360,
        "net_cap_rate": 0.0250,
        "vacancy_rate": 0.0350,
        "days_on_market": 46,
    },
    {
        "comuna": "Santiago Centro",
        "segment_type": "Entry",
        "uf_m2": 79.6,
        "gross_cap_rate": 0.0530,
        "net_cap_rate": 0.0410,
        "vacancy_rate": 0.1090,
        "days_on_market": 58,
    },
    {
        "comuna": "La Florida",
        "segment_type": "Mid-Market",
        "uf_m2": 73.5,
        "gross_cap_rate": 0.0500,
        "net_cap_rate": 0.0380,
        "vacancy_rate": 0.0820,
        "days_on_market": 52,
    },
    {
        "comuna": "Macul",
        "segment_type": "Mid-Market",
        "uf_m2": 75.0,
        "gross_cap_rate": 0.0490,
        "net_cap_rate": 0.0370,
        "vacancy_rate": 0.0790,
        "days_on_market": 56,
    },
    {
        "comuna": "Independencia",
        "segment_type": "Entry",
        "uf_m2": 63.2,
        "gross_cap_rate": 0.0510,
        "net_cap_rate": 0.0390,
        "vacancy_rate": 0.0940,
        "days_on_market": 64,
    },
    {
        "comuna": "San Miguel",
        "segment_type": "Entry",
        "uf_m2": 69.4,
        "gross_cap_rate": 0.0480,
        "net_cap_rate": 0.0360,
        "vacancy_rate": 0.1020,
        "days_on_market": 73,
    },
    {
        "comuna": "Estacion Central",
        "segment_type": "Entry",
        "uf_m2": 58.7,
        "gross_cap_rate": 0.0520,
        "net_cap_rate": 0.0370,
        "vacancy_rate": 0.1420,
        "days_on_market": 92,
    },
    {
        "comuna": "La Cisterna",
        "segment_type": "Entry",
        "uf_m2": 61.9,
        "gross_cap_rate": 0.0500,
        "net_cap_rate": 0.0380,
        "vacancy_rate": 0.0890,
        "days_on_market": 68,
    },
    {
        "comuna": "Cerrillos",
        "segment_type": "Mid-Market",
        "uf_m2": 59.8,
        "gross_cap_rate": 0.0490,
        "net_cap_rate": 0.0370,
        "vacancy_rate": 0.0850,
        "days_on_market": 61,
    },
    {
        "comuna": "Colina",
        "segment_type": "Houses",
        "uf_m2": 71.2,
        "gross_cap_rate": 0.0440,
        "net_cap_rate": 0.0340,
        "vacancy_rate": 0.0530,
        "days_on_market": 37,
    },
    {
        "comuna": "Puente Alto",
        "segment_type": "Houses",
        "uf_m2": 57.6,
        "gross_cap_rate": 0.0520,
        "net_cap_rate": 0.0410,
        "vacancy_rate": 0.0710,
        "days_on_market": 44,
    },
    {
        "comuna": "San Bernardo",
        "segment_type": "Houses",
        "uf_m2": 54.1,
        "gross_cap_rate": 0.0500,
        "net_cap_rate": 0.0390,
        "vacancy_rate": 0.0740,
        "days_on_market": 47,
    },
    {
        "comuna": "Lampa",
        "segment_type": "Houses",
        "uf_m2": 50.5,
        "gross_cap_rate": 0.0540,
        "net_cap_rate": 0.0430,
        "vacancy_rate": 0.0570,
        "days_on_market": 35,
    },
]
